config/routes.rb
Railsrumble::Application.routes.draw do
  
  resources :pages, :except => [:edit]

  devise_for :users, :controllers => { :sessions => "sessions" }

  root :to => "home#index"

end

app/views/pages/_form.html.erb
<%= form_for(@page, :html => { :multipart => true }) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <%= f.label :slug, "Slug: " %>
    <%= f.text_field :slug, :maxlength => 24 %><br />

    <%= f.label :title, "Title: " %>
    <%= f.text_field :title %><br />

    <%= f.label :subtitle, "Subtitle: " %>
    <%= f.text_field :subtitle %><br />

    <%= f.file_field :cover_photo %>
  </fieldset>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/_page.html.erb
<% content_for :title do %><%= @page.title %><% end %>
<% content_for :description do %><%= @page.subtitle %><% end %>

<% if @page.new_record? or signed_in? %>
<div id="account-menu">
  <ul class="unstyled">
    <% if signed_in? %>
      <li><a href="#" rel="tooltip" id="edit-header" data-placement="left" data-original-title="Edit header"><i class="icon-edit"></i></a></li>
      <li><a href="#" rel="tooltip" id="save-link" data-placement="left" data-original-title="Save page"><i class="icon-save"></i></a></li>
      <li><a href="<%= pages_path %>" rel="tooltip" data-placement="left" data-original-title="Manage pages"><i class="icon-file"></i></a></li>
      <li><a href="<%= destroy_user_session_url() %>" rel="tooltip" data-placement="left" data-original-title="Logout"><i class="icon-off"></i></a></li>
    <% else %>
      <li><a href="#" rel="tooltip" id="edit-header" data-placement="left" data-original-title="Edit header"><i class="icon-edit"></i></a></li>
      <li><a href="#modal-login" rel="tooltip" data-placement="left" data-original-title="Save page" data-toggle="modal"><i class="icon-save"></i></a></li>
    <% end %>
  </ul>
</div>

<div id="gradient-editor">
  <input type='text' id="gradient-left-color" />
  <input type='text' id="gradient-right-color" />
</div>
<% end %>

<header class="jumbotron subhead" id="overview" data-slug="<%= @page.slug %>" data-gradient-left="<%= @page.gradient_left %>" data-gradient-right="<%= @page.gradient_right %>">
  <div class="container">
    <h1 class="<%= "editable" if signed_in? or @page.new_record? %>"><%= @page.title %></h1>
    <p class="lead <%= "editable" if signed_in? or @page.new_record? %>"><%= @page.subtitle %></p>
  </div>
</header>

<div id="page" class="container">
  <div class="row">
    <div class="span3">
      <div class="span3 page-sidebar" data-spy="affix" data-offset-top="220">
        <ul class="nav nav-list page-sidenav section-nav <%= "do-draggable" if signed_in? or @page.new_record? %>">
          <% @page.sections.each_with_index do |section, section_index| %>
            <li>
              <% if signed_in? or @page.new_record? %><div class="remove-section"><b class="icon-remove"></b></div><% end %>
              <a href="#section-<%= section_index %>">
                <i class="icon-chevron-right"></i> <span><%= section.title %></span>
              </a>
            </li>
          <% end %>
        </ul>
        <% if signed_in? or @page.new_record? %>
          <ul class="nav nav-list page-sidenav">
            <li class="add-section">
              <a href="#">
                <i class="icon-plus"></i> Add Section
              </a>
            </li>
          </ul>
        <% end %>
      </div>
    </div>
    <div class="span9" id="section-container">
      <% @page.sections.each_with_index do |section, section_index| %>
        <section id="section-<%= section_index %>" data-id="<%= section.id %>">
          <div class="page-header">
            <h2 class="<%= "editable" if signed_in? or @page.new_record? %>" data-target="section-<%= section_index %>"><%= section.title %></h2>
          </div>
          <p class="lead <%= "editable" if signed_in? or @page.new_record? %>">
            <%= section.content %>
          </p>
        </section>
      <% end %>
    </div>
  </div>
</div>

<% if @page.new_record? and not signed_in? %>
  <div id="modal-login" class="modal hide fade">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h3>Sign up or Login <small>to save your page</small></h3>
    </div>
    <div class="modal-body">
      <%= form_for @user, {:url => '', :html => {:class => 'new_user form-horizontal'}} do |f| %>
        <div class="control-group">
          <label class="control-label" for="user_email">Email</label>
          <div class="controls">
            <%= f.email_field :email, :placeholder => 'email@example.com' %>
            <span class="help-inline">No spam here</span>
          </div>
        </div>
        <div class="control-group">
          <label class="control-label" for="user_password">Password</label>
          <div class="controls">
            <%= f.password_field :password, :placeholder => '********' %>
            <span class="help-inline">6+ chars</span>
          </div>
        </div>
        <div class="control-group">
          <div class="controls">
            <%= f.submit "Login or Sign up", :class => 'btn btn-primary' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/pages/edit.html.erb
<%= render 'page' %>

app/views/pages/index.html.erb
<% content_for :title do %>One Page - Manage your pages<% end %>

<div id="page-list" class="container-fluid">

  <div id="account-menu">
    <ul class="nav nav-pills nav-stacked">
      <li><%= link_to 'Logout', :destroy_user_session %></li>
    </ul>
  </div>

  <div class="row-fluid">
    <header class="span12">
      <h1>One Page<br/><small>Manage your pages</small></h1>
    </header>
  </div>

    <% @pages.each_with_index do |page, index| %>

      <% if index % 3 == 0 %>
        <div class="row-fluid">
      <% end %>

      <div class="page-thumb span4">
        <%= link_to page do %>
          <div class="page-thumb-head" <%= set_page_gradient_style(page) %>>
            <h2><%= page.title %></h2>
          </div>
        <% end %>
        <div class="page-thumb-controls">
          <span><%= page_url(page) %></span>
          <%= link_to page, :method => :delete, :confirm => 'Are your sure you want to delete this page? There is no turning back!' do %><i class="icon-trash"></i> Delete<% end %>
        </div>
      </div>

      <% if index % 3 == 2 %>
        </div>
      <% end %>

    <% end %>

    <% if @pages.size % 3 == 0 %>
      <div class="row-fluid">
    <% end %>

    <%= link_to new_page_path, :class => 'page-thumb page-new span4' do %>
      New Page
    <% end %>

    </div>
  
</div>

app/views/pages/new.html.erb
<%= render 'page' %>

app/views/pages/show.html.erb
<%= render 'page' %>